import { clearAuthSession, getAuthSession, setAuthSession } from './backendApi/core'
import { deleteUser, listUsers, login, register, updateUser } from './backendApi/auth'
import { saveFloorLayout } from './backendApi/layout'
import {
  createFloor,
  createMenuFolder,
  createMenuItem,
  createRestaurant,
  createWorker,
  deleteFloor,
  deleteOpeningHourOverride,
  deleteMenuFolder,
  deleteMenuItem,
  deleteRestaurant,
  deleteWorker,
  fetchRestaurantsGraph,
  getOpeningHourOverrides,
  getOpeningHours,
  listFloors,
  listRestaurants,
  updateFloor,
  updateMenuFolder,
  updateMenuItem,
  updateRestaurant,
  updateWorker,
  upsertOpeningHourOverride,
  upsertWeeklyOpeningHours,
} from './backendApi/restaurantResources'
import {
  addOrderLine,
  createReservation,
  deleteOrderLine,
  deleteReservation,
  deleteTableOrder,
  ensureOpenOrderId,
  fetchTableServiceState,
  listKitchenOrderLines,
  listTableReservations,
  updateOrderLine,
  updateReservation,
} from './backendApi/tableService'

export const backendApi = {
  login,
  register,
  listUsers,
  updateUser,
  deleteUser,
  setAuthSession,
  clearAuthSession,
  getAuthSession,
  fetchRestaurantsGraph,
  saveFloorLayout,
  fetchTableServiceState,
  ensureOpenOrderId,
  listRestaurants,
  createRestaurant,
  updateRestaurant,
  deleteRestaurant,
  listFloors,
  createFloor,
  updateFloor,
  deleteFloor,
  createWorker,
  updateWorker,
  deleteWorker,
  getOpeningHours,
  getOpeningHourOverrides,
  upsertWeeklyOpeningHours,
  upsertOpeningHourOverride,
  deleteOpeningHourOverride,
  createMenuFolder,
  updateMenuFolder,
  deleteMenuFolder,
  createMenuItem,
  updateMenuItem,
  deleteMenuItem,
  createReservation,
  listTableReservations,
  updateReservation,
  deleteReservation,
  addOrderLine,
  updateOrderLine,
  deleteOrderLine,
  deleteTableOrder,
  listKitchenOrderLines,
}
